### ISSUE TITLE
Overwrite Gemfile rather than create Gemfile.ordinaire

### ISSUE THREAD

**Issue by Nowaker** [nikolalsvk/ordinare#10]
Why create a separate file? People keep their files in git anyway.

--backup could be introduced to save an original file as Gemfile.backup or something but I don't think it's even necessary. 

Great project!

**Comment by nikolalsvk** [comment]
@Nowaker Thanks for submitting an issue :)

I don't know why I made ordinare to create a separate file, maybe I didn't want to overwrite peoples Gemfiles without their permission.

But you are totally right, people keep their Gemfile version controlled. I will make ordinare overwrite Gemfile and I will say it will do that in README.

Thanks for the support 🙇

**Comment by nikolalsvk** [comment]
This sould be taken care of inside https://github.com/nikolalsvk/ordinare/pull/11
