### ISSUE TITLE
What about --check option?

### ISSUE THREAD

**Issue by moofkit** [nikolalsvk/ordinare#13]
It will be useful after using it once to check that Gemfile is ordered. You can add check task and run it with rubocop and tests on CI.
WDYT?

**Comment by nikolalsvk** [comment]
@moofkit Great idea, that would be useful 👍 

Thanks for the suggestion, I will implement it 🙇

**Comment by moofkit** [comment]
Thanks, @nikolalsvk! Call me if you need some help)

**Comment by nikolalsvk** [comment]
@moofkit I've implemented `--check` option in [this PR](https://github.com/nikolalsvk/ordinare/pull/15)

If you want, you can try it out :)
